<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Kanchan" failures="2" tests="2" name="Default test(failed)" time="0.087" errors="0" timestamp="2024-05-20T21:51:57 IST">
  <testcase classname="failedRetryAnalyserRelated.FailedDemoRetryAna" name="test2" time="0.009">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at failedRetryAnalyserRelated.FailedDemoRetryAna.test2(FailedDemoRetryAna.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="failedRetryAnalyserRelated.FailedDemoRetryAna" name="test3" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failedRetryAnalyserRelated.FailedDemoRetryAna.test3(FailedDemoRetryAna.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="failedRetryAnalyserRelated.FailedDemoRetryAna" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
